{% set name = "geemap" %}
{% set version = "0.6.10" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 9f058b1c0d05590eacaff585b8742fe80cd91c6de064ca28468c155cf0f4fa7c

build:
  number: 0
  entry_points:
    - geemap=geemap.cli:main
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - bqplot
    - click
    - colour
    - earthengine-api
    - folium >=0.10.1
    - geeadd
    - geocoder
    - ipyfilechooser
    - ipyleaflet >=0.12.2
    - ipynb-py-convert
    - matplotlib
    - pillow
    - pyshp
    - python
    - pip

test:
  imports:
    - geemap
  commands:
    - geemap --help

about:
  home: "https://github.com/giswqs/geemap"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "A Python package for interactive mapping using Google Earth Engine and ipyleaflet"
  doc_url: https://geemap.readthedocs.io
  dev_url: https://github.com/giswqs/geemap

extra:
  recipe-maintainers:
    - giswqs
