{% set name = "geemap" %}
{% set version = "0.6.6" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: f0c7dd97db000d56710c861cb04a341b8ba287d6403df55abf64bfffbc258189

build:
  number: 0
  entry_points:
    - geemap=geemap.cli:main
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - bqplot
    - click
    - colour
    - earthengine-api
    - folium >=0.10.1
    - ipyfilechooser
    - ipyleaflet >=0.12.2
    - ipynb-py-convert
    - matplotlib
    - pyshp
    - python

test:
  imports:
    - geemap
  commands:
    - geemap --help

about:
  home: "https://github.com/giswqs/geemap"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "A Python package for interactive mapping using Google Earth Engine and ipyleaflet"
  doc_url: https://geemap.readthedocs.io
  dev_url: https://github.com/giswqs/geemap

extra:
  recipe-maintainers:
    - giswqs
