{% set name = "geemap" %}
{% set version = "0.5.5" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: f4c166e728807a9d9610e023a2e6026fa49cc21d24d4568c240531ae2374046d

build:
  number: 0
  entry_points:
    - geemap=geemap.cli:main
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - bqplot
    - click
    - earthengine-api
    - folium >=0.10.1
    - ipyleaflet >=0.12.2
    - ipynb-py-convert
    - python

test:
  imports:
    - geemap
  commands:
    - geemap --help

about:
  home: "https://github.com/giswqs/geemap"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "A Python package for interactive mapping using Google Earth Engine and ipyleaflet"
  doc_url: https://geemap.readthedocs.io
  dev_url: https://github.com/giswqs/geemap

extra:
  recipe-maintainers:
    - giswqs
