{% set name = "geemap" %}
{% set version = "0.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f19a49cab70c34d7442b1e70afedf4a6f05448d977fd610c73054749c1caa14c

build:
  number: 0
  entry_points:
    - geemap=geemap.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - bqplot
    - click
    - colour
    - earthengine-api >=0.1.230
    - ffmpeg-python
    - folium >=0.11.0
    - geeadd >=0.5.1
    - geocoder
    - geojson
    - googledrivedownloader
    - ipyevents
    - ipyfilechooser >=0.6.0
    - ipyleaflet <=0.14.0
    - ipynb-py-convert
    - ipytree
    - jupyterlab >=3.0.0
    - matplotlib
    - numpy
    - owslib
    - palettable
    - pandas
    - pillow
    - pycrs
    - pyshp >=2.1.3
    - python >=3.7
    - python-box
    - python-mss
    - sankee
    - voila
    - whiteboxgui
    - xyzservices

test:
  imports:
    - geemap
  commands:
    - geemap --help

about:
  home: https://geemap.org
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Earth Engine Python API and interactive mapping
  description: A Python package for interactive mapping with Google Earth Engine, ipyleaflet, and folium.
  doc_url: https://geemap.org
  dev_url: https://github.com/giswqs/geemap

extra:
  recipe-maintainers:
    - giswqs
